### ISSUE TITLE
Wrong progress bar?

### ISSUE THREAD

**Issue by sshyukriev** [abock/image-usb-stick#1]
I'm using your tool to write some SUSE Studio generated .raw files.
The only issue i can see is the the progress/percentage indicator is full after less than 1 minute and i suppose it shows only the time elapsed for formatting the USB stick.

Selected: USB_Flash_Disk (/dev/sdc) - 4 GB

WARNING: imaging /dev/sdc may result in data loss! Continue? [Y/N]: Y
100%  0:00:39  [================================================]  ETA 0:00:00

**Comment by abock** [comment]
I'm not really sure what you mean - from your output everything looks fine - 100%, the bar is all the way to other side, and ETA is 0 seconds.

It is possible for this progress data to be a little misleading in some cases, especially on smaller files since the user space writes can happen very quickly, but they are not yet synced out to the device by the kernel. From the tool's perspective, the writes are complete, and so the progress is reflected so, even if the buffers are still flushing to the device.

I could add a --sync option to force sync() calls after each write, but this would be bad for performance. Could be useful for helping debugging I guess.

In any regard, it's not clear to me what your issue is.

**Comment by sshyukriev** [comment]
In fact my .raw file is ~160 MB and the write process is over after 3-4 minutes, not after showing that the process is 100% completed
